# Generated by Django 3.0.8 on 2020-07-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200713_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquecode',
            name='receiver',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uniquecode',
            name='sender',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
